#!/bin/sh

# variables #

# backup target path
DESTPATH=/backups/externalA
# number of full duplicity backups to keep before autoremoval
DUPFULL=3
# big data locations
BDATA=".local/share/Steam .local/share/flatpak .var .steam snap"

mk_bu_dir() {
  if [ ! -d "$2" ] ; then
    mkdir -p "$2"
    chown "$1":"$1" "$2"
  fi
}

usr_bu_dup() { # working
  if ! which duplicity ; then
    echo "duplicity not installed"
  else
    mk_bu_dir "$1" "$2"
    su -c "duplicity \
      --full-if-older-than 30D \
      --no-encryption \
      --volsize=256 \
      --exclude-if-present .nobackup \
      --exclude=/home/${1}/Downloads \
      --exclude=/home/${1}/Videos \
      --exclude=/home/${1}/Music \
      /home/${1} \
      file://${2}" "$1"

    # stage two clean duplicity backup
    su -c "duplicity \
      remove-all-but-n-full ${DUPFULL} \
      --force \
      file://${2}" "$1"
  fi
}

big_data_bu() {
  if ! which rsync ; then
    echo "rsync not installed"
  else
    mk_bu_dir "$1" "$2"
    for dir in $BDATA ; do
      clear
      if [ -d /home/"$1"/"$dir" ] ; then
        echo "syncing ${dir}"
        rsync \
          -au \
          /home/"$1"/"$dir" \
          "$2"/
        echo "${dir} synced"
        sleep 5
      else
        echo "${dir} doesn't exist"
      fi
    done
    chown -R "$1":"$1" "$2"
  fi
}

for user in /home/* ; do
  UNAME=$(basename "$user")
  if [ "$UNAME" != root ] && \
     [ "$UNAME" != partimg ] && \
     [ "$UNAME" != lost+found ] ; then
  if [ $(chage -l "$UNAME" | grep Last | awk '{print $8}') = changed ] ; then
    continue
  else
    usr_bu_dup "$UNAME" "$DESTPATH"/DUPDATA/"$UNAME"
  fi
#    big_data_bu "$UNAME" "$DESTPATH"/BIGDATA/"$UNAME"
  fi
done
